# Generated by Django 3.2.16 on 2022-11-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, upload_to='posts/', verbose_name='Ваше фото')),
                ('city', models.TextField(verbose_name='Город проживания')),
                ('birth_day', models.TextField(verbose_name='Дата рождения')),
                ('sex', models.TextField(verbose_name='Пол')),
                ('nationality', models.TextField(verbose_name='Гражданство')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('carrer_objective', models.TextField(verbose_name='Желаемая должность')),
                ('education', models.TextField(verbose_name='Образование')),
                ('language', models.TextField(verbose_name='Языки')),
                ('employment', models.TextField(verbose_name='Тип занятости')),
                ('about_me', models.TextField(verbose_name='О себе')),
                ('phone_number', models.TextField(verbose_name='Номер телефона')),
                ('email', models.TextField(verbose_name='email')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.group')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
